spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

openai.api-key=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
openai.model=gpt-3.5-turbo